### PR TITLE
ADD: restore BPRO (BITP now) to list. Fix #511

### LINKED ISSUE #394: BPRO no longer available on iOS
On latest iOS version (1.2.1), BPRO is no longer available to be selected on the asset list.

It would be great to have it back without needing to manually add it. Thanks!

Screenshot:
BPRO on iOS

### LINKED ISSUE #511: Add BITP Mainnet as a default asset in RWallet
Name: BitPRO
Symbol: BITP
Address: 0x440cd83C160de5C96DDb20246815EA44C7Abbca8
https://explorer.rsk.co/address/0x440cd83c160de5c96ddb20246815ea44c7abbca8

### PR DESCRIPTION
**Pull request by ilmesi**
Added missing token BPRO

### CODE REVIEW

**Comment by chrisli30** [comment]
@ilmesi Thanks for adding the asset!

1. I think we should stick with the symbol on explorer, BITP. It will mislead users if the symbol is different in RWallet. What do you think?
    https://explorer.rsk.co/address/0x440cd83c160de5c96ddb20246815ea44c7abbca8
    image

1. Is it really necessary to add testnet token as well? The BITP is derivatives. It's not utility token like tRBTC and tRIF.

**Comment by franamati** [comment]
On 2, tRIFP exists too, maybe removing both for consistency.

**Comment by ilmesi** [comment]
No problem @chrisli30!

1- Sure, seems good to me. Although I'll ask devs from MoC about it since they published it with another symbol on their release notes.

**Comment by chrisli30** [comment]
@ilmesi 

1. Okay. I'm checking with MoC team.
2. We can have tBITP and tRIFP for now. Let's keep them.

**Comment by chrisli30** [comment]
@ilmesi 

Got the response. the symbol needs to be the same as the one shown in explorer, BITP. Could you update the PR?

We will keep tBITP and tRIFP.

Thanks.

**Comment by ilmesi** [comment]
@chrisli30 Done. I guess we've found out what happened with this token. The name was already included in the constants.js file it wasn't included in cointype list. I've replaced all the references for BPRO also. Whould you like a rebase ?

**Comment by chrisli30** [comment]
> @chrisli30 Done. I guess we've found out what happened with this token. The name was already included in the constants.js file but it wasn't included in cointype list. I've replaced all the references about BPRO also. Would you like a rebase ?

Sorry, do you mean merge with rebase? After approval you can merge the PR.

**Review by chrisli30 — APPROVED** [review]
Looks good!

**Pull request merged**
