### PR TITLE
chore: Remove WebView / Add env files

### PR DESCRIPTION
**Pull request by patogallaiovlabs**
The aim of this PR is to make the build process easier, by doing 2 things:
- Remove WebView component on `npm install`, so we don't have to do it manually.
- Add common environment files for Fastlane and Development process.

### CODE REVIEW

**Review by farinalvaro — APPROVED** [review]
LGTM

**Comment by jessgusclark** [comment]
I took a look at this and it installs fine, however, I don't understand the purpose of `rm_webview.sh`. Why do these files need to be deleted?

I also saw the temp env files. If these are to be used, then we should add instructions to the readme file on how to use them.

**Comment by patogallaiovlabs** [comment]
> I took a look at this and it installs fine, however, I don't understand the purpose of `rm_webview.sh`. Why do these files need to be deleted?
This is because Apple rejects apps with WebView injected.
https://github.com/rsksmart/rwallet#build-on-ios
But I'm not quite sure, could be because of old SDK, what are your thoughts?
> 
> I also saw the temp env files. If these are to be used, then we should add instructions to the readme file on how to use them.
Yep, I'll add a section or sthg. Cool

**Review by farinalvaro — APPROVED** [review]
LGTM

**Pull request merged**
