### PR TITLE
Minor change to English Language

### PR DESCRIPTION
**Pull request by bitcoinuser**

### CODE REVIEW

**Comment by bitcoinuser** [comment]
> A screenshot of the updated text is required.
> 
> By the way if we change English other language probably needs a change too.

photo_2020-08-06_18-33-40

**Comment by bitcoinuser** [comment]
> A screenshot of the updated text is required.
> 
> By the way if we change English other language probably needs a change too.



> A screenshot of the updated text is required.
> 
> By the way if we change English other language probably needs a change too.

I already changed the Portuguese Brazilian here: https://github.com/rsksmart/rwallet/pull/377

**Comment by chrisli30** [comment]
Great @bitcoinuser 

@imstar15 , let's make sure every other language other than En and Pt-BR have the correct wording as well.

**Comment by chrisli30** [comment]
@imstar15 这还有个遗留PR，其他的语言这个Currency改成Asset了吗？

**Pull request closed without merging**
